# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  i3-swallow = {
    pname = "i3-swallow";
    version = "7a9faed693b0da7df762a095fed512eca8c6414c";
    src = fetchgit {
      url = "https://github.com/jamesofarrell/i3-swallow";
      rev = "7a9faed693b0da7df762a095fed512eca8c6414c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1fq9cvisimgyza8c91bkill9wgyj7ac9sf9yz87npc1smlgscibd";
    };
  };
  kickoff = {
    pname = "kickoff";
    version = "8d56b89ac115dca99b5edbd603bd15e20eb1f5a4";
    src = fetchgit {
      url = "https://github.com/j0ru/kickoff";
      rev = "8d56b89ac115dca99b5edbd603bd15e20eb1f5a4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1f20wl7d7qx0xz2n5p4vw99l321f4ima2szrfn3jlcgvx9shhp36";
    };
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchgit {
      url = "https://github.com/mlvzk/manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1b7xi8c2drbwzfz70czddc4j33s7g1alirv12dwl91hbqxifx8qs";
    };
  };
}
