name: Changelog

on:
  release:
    types: [published]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Generate change log
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
